'use strict';

var demos = [
	{
		iframe: 'intro.html',
		screen: 'Intro',
	},
	{
		iframe: 'dataworld/',
		title: 'Dataworld',
		author: 'xplsv',
		rank: 7,
		compo: 'pc demo',
		party: 'NVScene 2015',
		pouet: 65257,
		duration: 1*60 + 30,
	},
	{
		iframe: 'air-to-ground/',
		title: 'Air to Ground',
		author: 'Wide Load',
		rank: 13,
		compo: 'combined demo',
		party: 'Assembly 2015',
		pouet: 66114,
		duration: 3*60 + 2,
	},
	{
		iframe: 'box-of-quadtrip/',
		title: 'The Box Of Quadtrip',
		author: 'Quadtrip',
		rank: 2,
		compo: 'alternative demo',
		party: 'The Alternative Party Lite 2014',
		pouet: 64398,
		duration: 2*60 + 49,
	},
	// {
	// 	iframe: 'clrfl-shdr/',
	// 	title: 'clrfl shdr',
	// 	author: 'Walther',
	// 	rank: 10,
	// 	compo: 'combined 4k',
	// 	party: 'Assembly 2015',
	// 	pouet: 66080,
	// 	duration: 1*60,
	// },
	{
		iframe: 'gen_field/Demo.html',
		title: 'gen_field',
		author: 'hamuha',
		rank: 9,
		compo: 'combined demo',
		party: 'TokyoDemoFest 2015',
		pouet: 65134,
		duration: 1*60 + 6,
	},
	{
		iframe: 'narrow/base.html',
		title: 'Narrow',
		author: 'Wide Load',
		rank: 1,
		compo: 'alternative demo',
		party: 'The Alternative Party Lite 2014',
		pouet: 64397,
		duration: 2*60 + 14,
	},
	{
		iframe: 'balena/',
		title: 'BALENA',
		author: 'hamuha',
		rank: 6,
		compo: 'combined demo',
		party: 'TokyoDemoFest 2015',
		pouet: 65117,
		duration: 3*60 + 28,
	},
	{
		iframe: 'ninkasi/',
		title: 'Ninkasi',
		author: 'trbl',
		rank: 1,
		compo: 'alternative demo',
		party: 'Evoke 2015',
		pouet: 66100,
		duration: 1*60 + 15,
		comment: 'Actually, this is not WebGL! Sorry.',
	},
	{
		iframe: 'small-worlds/primitive-iwanttoseeotherworlds.html',
		title: 'I Want To See Small Worlds',
		author: 'Primitive',
		rank: 6,
		compo: 'combined demo',
		party: 'Assembly 2015',
		pouet: 66088,
		duration: 3*60 + 20,
	},
	{
		iframe: 'hungry-for-more/hungry-for-more.html',
		title: 'Hungry for more',
		author: 'tmp',
		rank: 6,
		compo: 'pc demo',
		party: 'Evoke 2015',
		pouet: 66083,
		duration: 1*60 + 34,
	},
	{
		iframe: 'fractures/base.html',
		title: 'Fractures',
		author: 'Wide Load',
		rank: 6,
		compo: 'pc demo',
		party: 'Payback 2015',
		pouet: 64989,
		duration: 2*60,
	},
	{
		iframe: 'destroy-all-humans/',
		title: 'Destroy All Humans',
		author: 'jumalauta',
		rank: 2,
		compo: 'combined demo',
		party: 'Jumalauta 15 years 2015',
		pouet: 66351,
		duration: 1*60 + 10,
	},
	// {
	// 	iframe: 'encore/demo/index.htm',
	// 	title: 'Encore',
	// 	author: 'The Royal Elite Ninjas Inc.',
	// 	rank: 10,
	// 	compo: 'combined demo',
	// 	party: 'Assembly 2015',
	// 	pouet: 66071,
	// 	duration: 1*60 + 34,
	// },
	// {
	// 	iframe: 'divination/',
	// 	title: 'Divination',
	// 	author: 'Quadtrip',
	// 	rank: 11,
	// 	compo: 'combined demo',
	// 	party: 'Assembly 2015',
	// 	pouet: 66064,
	// 	duration: 5*60 + 27
	// },
	{
		iframe: 'BLCK4777/BLCK4777.htm',
		title: 'BLCK4777',
		author: 'ribbon',
		rank: 1,
		compo: 'pc 1k',
		party: 'Assembly 2015',
		pouet: 66035,
		duration: 1*60 + 50,
		comment: 'Actually, this is not WebGL! Sorry.',
	},
	{
		iframe: 'other-worlds/primitive-_-i_want_to_see_other_worlds.html',
		title: 'I Want To See Other Worlds',
		author: 'Primitive',
		rank: 3,
		compo: 'combined demo',
		party: 'Solskogen 2015',
		pouet: 65971,
		duration: 3*60 + 13,
	},
	{
		iframe: 'everything-is-fashion/demo.png.html',
		title: 'Everything is fashion',
		author: 'Ninjadev',
		rank: 2,
		compo: 'combined demo',
		party: 'Solskogen 2015',
		pouet: 65978,
		duration: 2*60 + 30,
	},
	{
		iframe: 'nvscene/',
		title: 'NVSCENE 2015',
		author: 'Cabbibo',
		rank: 5,
		compo: 'combined demo',
		party: 'Kindergarten 2014',
		pouet: 64348,
		duration: 3*60 + 10,
	},
	{
		iframe: 'luxe/',
		title: 'Luxe',
		author: 'holon',
		rank: 1,
		compo: 'combined demo/intro',
		party: 'Deadline 2015',
		pouet: 66463,
		duration: 2*60 + 54,
	},
	{
		window: '//localhost/#password',
		title: 'Touch Me Together',
		author: 'tmp',
		rank: 3,
		compo: 'game',
		party: 'Revision 2015',
		pouet: 66483,
		duration: 5*60,
	},
	{
		iframe: 'demos.html',
		screen: 'Outro',
	},
];
